"""Tests for LLM call card contract in session detail trace (v9).

v9 renders LLM calls via sdt.llm_call_card macro in session_detail_timeline.html:
- LLM call cards: .sd-llm-card
- Tool batches: .sd-tool-group
- Payload buttons: data-action="open-payload" with data-payload-id
"""

from pathlib import Path

TEMPLATE_DIR = Path(__file__).parents[2] / "src" / "session_browser" / "web" / "templates"
COMPONENTS = TEMPLATE_DIR / "components"


def _session_source():
    return (TEMPLATE_DIR / "session.html").read_text(encoding="utf-8")


def _timeline_component():
    return (COMPONENTS / "session_detail_timeline.html").read_text(encoding="utf-8")


def _primitives_component():
    return (COMPONENTS / "session_detail_primitives.html").read_text(encoding="utf-8")


# ── LLM call card structure (v9 component) ──────────────────────────


def test_has_llm_call_card():
    """Timeline component must define llm_call_card macro."""
    source = _timeline_component()
    assert "macro llm_call_card" in source, (
        "Timeline must define llm_call_card macro"
    )


def test_llm_call_card_has_header():
    """LLM call card must have header with title, model, status."""
    source = _timeline_component()
    assert "sd-card-head" in source, "Card must have header"
    assert "sd-card-title" in source, "Card must have title"
    assert "sd-llm-card" in source, "Must have llm card class"


def test_llm_call_card_has_metrics():
    """LLM call card must have a metrics section."""
    source = _timeline_component()
    assert "sd-metrics" in source, "Card must have metrics section"


def test_llm_call_card_has_payload_buttons():
    """LLM call card must have payload buttons."""
    source = _timeline_component()
    assert "open-payload" in source, "Card must have open-payload buttons"
    # data-payload-id is generated by sdp.button() macro in primitives
    prim = _primitives_component()
    assert "data-payload-id" in prim, "Primitives must define data-payload-id"


# ── Tool calls in LLM call context ──────────────────────────────────


def test_tool_batch_macro_exists():
    """Timeline must have tool_batch macro."""
    source = _timeline_component()
    assert "macro tool_batch" in source, "Timeline must define tool_batch macro"


def test_tool_batch_has_data_attrs():
    """Tool batch must have data attributes for identification."""
    source = _timeline_component()
    assert "data-tool-batch-id" in source, "Tool batch must have data-tool-batch-id"
    assert "data-tool-call-id" in source, "Tool rows must have data-tool-call-id"


def test_tool_batch_has_result_buttons():
    """Tool rows must have payload result buttons."""
    source = _timeline_component()
    assert "open-payload" in source, "Tool rows must have open-payload buttons"


# ── Session uses component macros ───────────────────────────────────


def test_session_uses_trace_round_macro():
    """session.html must use sdt.trace_round for rendering rounds."""
    source = _session_source()
    assert "sdt.trace_round" in source, "Session must use sdt.trace_round macro"


# ── Payload keys in view model ──────────────────────────────────────


def test_payload_keys_in_routes():
    """routes.py view model must generate payload IDs for LLM calls."""
    routes = (Path(__file__).parents[2] / "src" / "session_browser" / "web" / "routes.py").read_text(encoding="utf-8")
    assert "context_payload_id" in routes, "View model must generate context_payload_id"
    assert "response_payload_id" in routes, "View model must generate response_payload_id"


# ── CSS classes ─────────────────────────────────────────────────────

_TIMELINE_CSS = Path(__file__).parents[2] / "src" / "session_browser" / "web" / "static" / "css" / "session-detail.css"


def _read_timeline_css():
    return _TIMELINE_CSS.read_text(encoding="utf-8")


def test_css_has_sd_llm_card_styles():
    """session-detail.css must contain card styles for LLM calls."""
    css = _read_timeline_css()
    # LLM card uses base .sd-card class + .sd-llm-body
    assert ".sd-card" in css, "CSS must define .sd-card styles"
    assert ".sd-card-head" in css, "CSS must define .sd-card-head styles"
    assert ".sd-card-title" in css, "CSS must define .sd-card-title styles"
    assert ".sd-llm-body" in css, "CSS must define .sd-llm-body styles"
    assert ".sd-metrics" in css, "CSS must define .sd-metrics styles"


def test_css_has_tool_group_styles():
    """session-detail.css must contain .sd-tool-group styles."""
    css = _read_timeline_css()
    assert ".sd-tool-group" in css, "CSS must define .sd-tool-group styles"
    assert ".sd-tool-row" in css, "CSS must define .sd-tool-row styles"
