"""会话详情追踪中 LLM payload 与事件行契约测试。

Expanded timeline 不再渲染 LLM call card:
- LLM usage / attribution 入口在 round row 和 payload modal 表达
- expanded detail 保留 user/assistant/tool/subagent 事件行
- Payload 按钮: data-action="open-payload" 带 data-payload-id
"""

import pytest

from pathlib import Path

TEMPLATE_DIR = Path(__file__).parents[2] / "src" / "session_browser" / "web" / "templates"
COMPONENTS = TEMPLATE_DIR / "components"
TIMELINE_FILE = COMPONENTS / "session_detail_timeline.html"
TIMELINE_DIR = COMPONENTS / "session_detail_timeline"


def _read_template_with_splits(main_file, split_dir):
    """Read main template file and all split subdirectory files (if they exist)."""
    parts = []
    if main_file.exists():
        parts.append(main_file.read_text(encoding="utf-8"))
    if split_dir.is_dir():
        for f in sorted(split_dir.glob("*.html")):
            parts.append(f.read_text(encoding="utf-8"))
    return "\n".join(parts)


def _session_source():
    return (TEMPLATE_DIR / "session.html").read_text(encoding="utf-8")


def _timeline_component():
    return _read_template_with_splits(TIMELINE_FILE, TIMELINE_DIR)


def _primitives_component():
    return (COMPONENTS / "session_detail_primitives.html").read_text(encoding="utf-8")


# ── LLM payload actions without expanded LLM card ───────────────────


def _timeline_event_macro() -> str:
    source = _timeline_component()
    start = source.find("{% macro timeline_event")
    end = source.find("{%- endmacro %}", start)
    return source[start:end]


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_timeline_event_does_not_render_llm_cards():
    """Expanded timeline must not render LLM summary or legacy LLM call cards."""
    event_macro = _timeline_event_macro()
    assert 'item.type == "llm_summary"' in event_macro
    assert 'item.type == "llm_call"' in event_macro
    assert "llm_summary_event(item)" not in event_macro
    assert "llm_call_card(item)" not in event_macro


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_user_message_row_has_payload_button():
    """User message must render as its own event row with payload access."""
    source = _timeline_component()
    assert "macro user_message_event" in source, "Timeline must define user message row"
    assert "USER" in source, "User message row must have USER kind"
    assert 'data-payload-kind="message.user"' in source, "User message payload kind missing"
    assert "sdp.button('Payload'" in source, "User message row must expose payload button"


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_llm_attribution_actions_are_direct_labels():
    """LLM attribution actions stay available through direct request/response labels."""
    source = _timeline_component()
    assert "macro attribution_actions" in source
    assert "attribution_chip(request, 'request')" in source
    assert "attribution_chip(response, 'response')" in source


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_payload_buttons_have_payload_ids():
    """Payload buttons must use data-payload-id generated by primitives."""
    assert "open-payload" in _timeline_component(), "Event rows must have open-payload buttons"
    # data-payload-id 由 primitives 中的 sdp.button() 宏生成
    prim = _primitives_component()
    assert "data-payload-id" in prim, "Primitives must define data-payload-id"


# ── LLM 调用上下文中的工具调用 ──────────────────────────────────


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_tool_batch_macro_exists():
    """Timeline must have tool_batch macro."""
    source = _timeline_component()
    assert "macro tool_batch" in source, "Timeline must define tool_batch macro"


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_tool_batch_has_data_attrs():
    """Tool batch must have data attributes for identification."""
    source = _timeline_component()
    assert "data-tool-batch-id" in source, "Tool batch must have data-tool-batch-id"
    assert "data-tool-call-id" in source, "Tool rows must have data-tool-call-id"


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_tool_batch_has_result_buttons():
    """Tool rows must have payload result buttons."""
    source = _timeline_component()
    assert "open-payload" in source, "Tool rows must have open-payload buttons"


# ── Session uses component macros ───────────────────────────────────


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_session_uses_trace_round_macro():
    """session.html must use sdt.trace_round for rendering rounds."""
    source = _session_source()
    assert "sdt.trace_round" in source, "Session must use sdt.trace_round macro"


# ── Payload keys in view model ──────────────────────────────────────


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_payload_keys_in_routes():
    """View model must generate payload IDs for LLM calls."""
    base = Path(__file__).parents[2] / "src" / "session_browser" / "web"
    routes = (base / "routes.py").read_text(encoding="utf-8")
    view_model = (base / "session_detail" / "view_model.py").read_text(encoding="utf-8")
    source = routes + "\n" + view_model
    assert "context_payload_id" in source, "View model must generate context_payload_id"
    assert "response_payload_id" in source, "View model must generate response_payload_id"


# ── CSS classes ─────────────────────────────────────────────────────

_TIMELINE_CSS = Path(__file__).parents[2] / "src" / "session_browser" / "web" / "static" / "css" / "session-detail.css"
_TIMELINE_CSS_DIR = _TIMELINE_CSS.parent / "session-detail"


def _read_css_with_splits(main_file, split_dir):
    """Read main CSS file and all split subdirectory files (if they exist)."""
    parts = []
    if main_file.exists():
        parts.append(main_file.read_text(encoding="utf-8"))
    if split_dir.is_dir():
        for f in sorted(split_dir.glob("*.css")):
            parts.append(f.read_text(encoding="utf-8"))
    return "\n".join(parts)


def _read_timeline_css():
    return _read_css_with_splits(_TIMELINE_CSS, _TIMELINE_CSS_DIR)


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_css_has_event_row_styles():
    """session-detail.css must contain compact event row styles."""
    css = _read_timeline_css()
    assert ".sd-event-row" in css, "CSS must define event row styles"
    assert ".sd-tool-group--flat" in css, "CSS must define flat event group styles"
    assert ".sd-timeline-dot--user" in css, "CSS must define user message dot styles"


@pytest.mark.contract_case("DATA-PRESENTER-009")
def test_css_has_tool_group_styles():
    """session-detail.css must contain .sd-tool-group styles."""
    css = _read_timeline_css()
    assert ".sd-tool-group" in css, "CSS must define .sd-tool-group styles"
    assert ".sd-tool-row" in css, "CSS must define .sd-tool-row styles"
