"""Deterministic tests: LLM call card payload semantics and token clarity (v9).

v9 architecture:
- LLM call cards rendered via sdt.llm_call_card macro
- Payload buttons generated by sdp.button() macro with data-payload-id
- Payload IDs and payload map generated in routes.py view model
- No inline data-payload-type in templates; routing is ID-based
"""

from __future__ import annotations

from pathlib import Path

import pytest

TEMPLATE_DIR = (
    Path(__file__).parents[2]
    / "src" / "session_browser" / "web" / "templates"
)
ROUTES = (
    Path(__file__).parents[2]
    / "src" / "session_browser" / "web" / "routes.py"
)


def _read_routes() -> str:
    return ROUTES.read_text(encoding="utf-8")


class TestLLMCallCardActionsRenamed:
    """LLM call card buttons use payload IDs from view model."""

    def test_context_payload_id_generated(self):
        """View model must generate context_payload_id for LLM calls."""
        routes = _read_routes()
        assert "context_payload_id" in routes, (
            "View model must generate context_payload_id"
        )

    def test_response_payload_id_generated(self):
        """View model must generate response_payload_id for LLM calls."""
        routes = _read_routes()
        assert "response_payload_id" in routes, (
            "View model must generate response_payload_id"
        )

    def test_request_button_in_macro(self):
        """LLM call card macro must have Request button (renamed from Context)."""
        timeline = (TEMPLATE_DIR / "components" / "session_detail_timeline.html").read_text(encoding="utf-8")
        assert "sdp.button('Request'" in timeline, "Template must have Request button"

    def test_response_button_in_macro(self):
        """LLM call card macro must have Response button."""
        timeline = (TEMPLATE_DIR / "components" / "session_detail_timeline.html").read_text(encoding="utf-8")
        assert "sdp.button('Response'" in timeline, "Template must have Response button"


class TestProviderUsageTooltip:
    """Input token metric must have provider usage explanation."""

    def test_input_metric_present(self):
        """Template must include Input metric label."""
        timeline = (TEMPLATE_DIR / "components" / "session_detail_timeline.html").read_text(encoding="utf-8")
        assert "Input" in timeline, "Template must include Input metric label"

    def test_input_tokens_in_routes(self):
        """View model must reference input_tokens."""
        routes = _read_routes()
        assert "input_tokens" in routes or "input" in routes, (
            "View model must reference input_tokens"
        )


class TestPartialCaptureWarning:
    """Warning must appear when input tokens are high but captured context is small."""

    def test_warning_condition_in_routes(self):
        """View model must handle partial context capture."""
        routes = _read_routes()
        # The view model processes request_full and context data
        assert "request_full" in routes, (
            "View model must reference request_full for partial capture"
        )

    def test_missing_reason_in_routes(self):
        """View model must handle request_payload_missing_reason."""
        routes = _read_routes()
        assert "missing_reason" in routes or "missing" in routes.lower(), (
            "View model must handle missing payload reason"
        )


class TestPayloadMapUpdated:
    """Payload map in view model must use proper types."""

    def test_pmap_has_context_type(self):
        """View model payload map must register context type."""
        routes = _read_routes()
        assert "context" in routes.lower(), (
            "View model must register context payload type"
        )

    def test_pmap_has_response_type(self):
        """View model payload map must register response type."""
        routes = _read_routes()
        assert "response" in routes.lower(), (
            "View model must register response payload type"
        )


class TestPayloadUnavailableMessage:
    """When no payload is available, show a clear message."""

    def test_unavailable_message_in_js(self):
        """JS must show message when payload is unavailable."""
        js = (Path(__file__).resolve().parents[2]
              / "src" / "session_browser" / "web" / "static" / "js"
              / "session_detail_timeline.js").read_text(encoding="utf-8")
        assert "unavailable" in js.lower() or "payload" in js.lower(), (
            "JS must have unavailable payload message"
        )
