"""Tests for timeline preview user input tag."""

from __future__ import annotations

import pytest


class TestPreviewTagRendersForUserInput:
    """Verify quote text tag renders when round has user input."""

    def test_tag_present_for_user_input(self):
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        assert "preview-tag--user" in content
        assert ">User</span>" in content

    def test_tag_condition_checks_user_msg_content(self):
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        # The tag should be conditional on user_msg.content
        assert "round.user_msg.content" in content
        assert "preview-tag--user" in content

    def test_tag_has_descriptive_tooltip(self):
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        assert "This round includes user input" in content


class TestPreviewTagDoesNotLeakUserContent:
    """Verify user input content is NOT exposed in preview."""

    def test_tag_tooltip_no_user_content(self):
        """Tag tooltip should be generic, not contain user content."""
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        # The tag tooltip is static text, not dynamic user content
        assert "preview-tag--user" in content

    def test_preview_tooltip_no_user_content(self):
        """Preview cell tooltip should only use preview_text, not user_msg.content."""
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        # The data-tooltip should use preview_text only
        # Check that preview-cell data-tooltip doesn't reference user_msg.content directly
        lines = content.split("\n")
        for line in lines:
            if "preview-cell" in line and "data-tooltip" in line:
                assert "user_msg.content" not in line, (
                    f"Preview cell tooltip should not contain user_msg.content: {line}"
                )


class TestPreviewTagPlacement:
    """Verify tag appears before preview text."""

    def test_tag_before_text(self):
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        # The tag should come before the preview_text output in template order
        tag_pos = content.find("preview-tag--user")
        preview_pos = content.find("round.preview_text")
        assert tag_pos > 0, "Preview tag not found"
        assert preview_pos > 0, "Preview text output not found"
        # Within the same round block, tag should come before preview_text
        assert tag_pos < preview_pos, "Preview tag should come before preview_text"


class TestPreviewCellNoSafe:
    """Verify preview cell rendering is safe."""

    def test_preview_safe_filter_usage(self):
        """preview_text uses | safe because it's pre-sanitized HTML from the normalizer."""
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        # The template uses | safe on round.preview_text (generated by normalizer, not raw user input)
        # and also provides a safe fallback via striptags for the description
        assert "preview_text | striptags" in content, \
            "Should use striptags for safe description display"


class TestPreviewTextTruncation:
    """Verify preview text truncation is preserved."""

    def test_truncation_at_120_chars(self):
        with open("src/session_browser/web/templates/session.html") as f:
            content = f.read()
        assert "[:80]" in content
