package com.feipi.session.browser.quality.gates.rules;

import com.feipi.session.browser.quality.gates.core.JavaSourceSet.ParsedSource;
import com.feipi.session.browser.quality.gates.core.QualityContext;
import com.feipi.session.browser.quality.gates.core.QualityRule;
import com.feipi.session.browser.quality.gates.core.QualityViolation;
import com.sun.source.tree.ClassTree;
import com.sun.source.tree.MethodTree;
import com.sun.source.tree.NewClassTree;
import com.sun.source.tree.Tree;
import com.sun.source.tree.VariableTree;
import com.sun.source.util.TreePathScanner;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Pattern;
import javax.lang.model.element.Modifier;

/** 使用 compiler AST 生成并校验 Java public API baseline。 */
public final class JavaApiSnapshotRule implements QualityRule {

  private static final Pattern ANNOTATION =
      Pattern.compile("@\\w+(?:\\.\\w+)*(?:\\s*\\([^()]*\\))?\\s*");
  private static final Pattern SPACE = Pattern.compile("\\s+");

  @Override
  public String id() {
    return "java-api-snapshot";
  }

  @Override
  public boolean usesChangedFiles() {
    return false;
  }

  @Override
  public List<QualityViolation> check(QualityContext context) throws Exception {
    var current = generate(context);
    if (context.writeApiSnapshot()) {
      Files.createDirectories(context.apiSnapshot().toAbsolutePath().getParent());
      Files.writeString(context.apiSnapshot(), current, StandardCharsets.UTF_8);
      return List.of();
    }
    if (!Files.exists(context.apiSnapshot())) {
      return List.of(violation("JAVA_API_SNAPSHOT_MISSING", "Java API baseline 不存在", ""));
    }
    var expected = Files.readString(context.apiSnapshot(), StandardCharsets.UTF_8);
    if (expected.equals(current)) {
      return List.of();
    }
    var expectedLines = new LinkedHashSet<>(expected.lines().toList());
    var currentLines = new LinkedHashSet<>(current.lines().toList());
    var violations = new ArrayList<QualityViolation>();
    expectedLines.stream()
        .filter(line -> !currentLines.contains(line))
        .forEach(
            line ->
                violations.add(
                    violation(
                        "JAVA_API_REMOVED_OR_CHANGED", "Java public API 与 baseline 不一致", line)));
    currentLines.stream()
        .filter(line -> !expectedLines.contains(line))
        .forEach(
            line ->
                violations.add(
                    violation(
                        "JAVA_API_ADDED_OR_CHANGED", "Java public API 与 baseline 不一致", line)));
    if (violations.isEmpty()) {
      violations.add(violation("JAVA_API_SNAPSHOT_FORMAT", "Java API baseline 格式不一致", ""));
    }
    return violations;
  }

  /** 生成与 baseline contract 一致的稳定文本。 */
  public static String generate(QualityContext context) {
    var lines = new TreeSet<String>();
    for (var source : context.sources().sources()) {
      var roots = new TypeCollector(source).collect();
      visitRegion(context, source, flatten(roots), null, false, lines);
    }
    return "# Java public API snapshot\n"
        + "# Generated by runJavaQualityGates --write-api-snapshot\n"
        + "# Update only after approving intentional public API changes.\n\n"
        + String.join("\n", lines)
        + "\n";
  }

  private static void visitRegion(
      QualityContext context,
      ParsedSource source,
      List<TypeNode> nodes,
      String prefix,
      boolean nested,
      Set<String> output) {
    for (var node : nodes) {
      var modifiers = node.tree().getModifiers().getFlags();
      var visible =
          nested
              ? !modifiers.contains(Modifier.PRIVATE)
              : modifiers.contains(Modifier.PUBLIC) || modifiers.contains(Modifier.PROTECTED);
      if (!visible) {
        continue;
      }
      var packageName = source.unit().getPackageName().toString();
      var qualified = (prefix == null ? packageName : prefix) + "." + node.tree().getSimpleName();
      appendType(context, source, node.tree(), qualified, output);
      visitRegion(context, source, flatten(node.children()), qualified, true, output);
    }
  }

  private static List<TypeNode> flatten(List<TypeNode> roots) {
    var result = new ArrayList<TypeNode>();
    for (var root : roots) {
      result.add(root);
      result.addAll(flatten(root.children()));
    }
    return result;
  }

  private static void appendType(
      QualityContext context,
      ParsedSource source,
      ClassTree tree,
      String qualified,
      Set<String> output) {
    var flags = tree.getModifiers().getFlags();
    var visibility = flags.contains(Modifier.PROTECTED) ? "protected" : "public";
    var kind = kind(tree);
    var module = source.relativePath().split("/")[1];
    var header = canonical(typeHeader(context, source, tree));
    header = normalize(header.replaceFirst("\\b(public|protected|private)\\b\\s*", ""));
    output.add("type " + qualified + " " + visibility + " " + kind + " [" + module + "] " + header);
    if (tree.getKind() == Tree.Kind.RECORD) {
      appendComponents(context, source, tree, qualified, output);
    } else if (tree.getKind() == Tree.Kind.ENUM) {
      appendEnumConstants(context, source, tree, qualified, output);
    }
    appendMembers(context, source, tree, qualified, output);
  }

  private static void appendComponents(
      QualityContext context,
      ParsedSource source,
      ClassTree tree,
      String qualified,
      Set<String> output) {
    // 兼容既有 baseline：旧 owner 不把带类型参数的 record 识别为 component source。
    if (!tree.getTypeParameters().isEmpty()) {
      return;
    }
    var positions = context.sources().docTrees().getSourcePositions();
    var body = bodyStart(context, source, tree);
    for (var member : tree.getMembers()) {
      if (!(member instanceof VariableTree variable)) {
        continue;
      }
      var start = positions.getStartPosition(source.unit(), member);
      var end = positions.getEndPosition(source.unit(), member);
      if (start < 0 || start >= body) {
        continue;
      }
      var declaration = canonical(mask(source.text().substring((int) start, (int) end)));
      declaration = normalize(declaration.replaceFirst("\\bfinal\\b\\s*", ""));
      var name = variable.getName().toString();
      var type = normalize(declaration.substring(0, declaration.lastIndexOf(name)));
      output.add("component " + qualified + " " + name + ": " + type);
    }
  }

  private static void appendEnumConstants(
      QualityContext context,
      ParsedSource source,
      ClassTree tree,
      String qualified,
      Set<String> output) {
    var positions = context.sources().docTrees().getSourcePositions();
    var body = bodyStart(context, source, tree);
    var end = (int) positions.getEndPosition(source.unit(), tree);
    if (mask(source.text().substring(body, end)).indexOf(';') < 0) {
      return;
    }
    for (var member : tree.getMembers()) {
      if (isEnumConstant(member)) {
        var variable = (VariableTree) member;
        var start = (int) positions.getStartPosition(source.unit(), variable);
        var variableEnd = (int) positions.getEndPosition(source.unit(), variable);
        var declaration = mask(source.text().substring(start, variableEnd)).trim();
        if (declaration.startsWith(variable.getName().toString())) {
          output.add("enum-constant " + qualified + " " + variable.getName());
        }
      }
    }
  }

  private static void appendMembers(
      QualityContext context,
      ParsedSource source,
      ClassTree tree,
      String qualified,
      Set<String> output) {
    var implicitPublic =
        tree.getKind() == Tree.Kind.INTERFACE || tree.getKind() == Tree.Kind.ANNOTATION_TYPE;
    for (var member : tree.getMembers()) {
      if (member instanceof ClassTree
          || (tree.getKind() == Tree.Kind.ENUM && isEnumConstant(member))) {
        continue;
      }
      var flags =
          switch (member) {
            case MethodTree method -> method.getModifiers().getFlags();
            case VariableTree variable -> variable.getModifiers().getFlags();
            default -> Set.<Modifier>of();
          };
      if (!implicitPublic
          && !flags.contains(Modifier.PUBLIC)
          && !flags.contains(Modifier.PROTECTED)) {
        continue;
      }
      var visibility = flags.contains(Modifier.PROTECTED) ? "protected" : "public";
      var raw = memberHeader(context, source, member);
      var canonical = canonical(raw).replaceFirst("\\b(public|protected|private)\\b\\s*", "");
      canonical = normalize(canonical);
      if (canonical.contains("(") && canonical.contains(")")) {
        var beforeParenthesis = canonical.substring(0, canonical.indexOf('(')).trim();
        var tokens = beforeParenthesis.split("\\s+");
        var name = tokens.length == 0 ? "" : tokens[tokens.length - 1];
        var constructor = name.equals(tree.getSimpleName().toString());
        output.add(
            (constructor ? "constructor " : "method ")
                + qualified
                + " "
                + visibility
                + " "
                + canonical);
      } else if (member instanceof MethodTree method && method.getReturnType() == null) {
        output.add(
            "constructor " + qualified + " " + visibility + " " + tree.getSimpleName() + "()");
      } else if (member instanceof VariableTree variable) {
        var name = variable.getName().toString();
        var declaration = canonical.split("=", 2)[0].trim();
        var nameIndex = declaration.lastIndexOf(name);
        if (nameIndex > 0) {
          output.add(
              "field "
                  + qualified
                  + " "
                  + visibility
                  + " "
                  + name
                  + ": "
                  + declaration.substring(0, nameIndex).trim());
        }
      }
    }
  }

  private static String typeHeader(QualityContext context, ParsedSource source, ClassTree tree) {
    var positions = context.sources().docTrees().getSourcePositions();
    var start = (int) positions.getStartPosition(source.unit(), tree);
    var lineStart = source.text().lastIndexOf('\n', start) + 1;
    return mask(source.text().substring(lineStart, bodyStart(context, source, tree)));
  }

  private static int bodyStart(QualityContext context, ParsedSource source, ClassTree tree) {
    var start =
        (int)
            context.sources().docTrees().getSourcePositions().getStartPosition(source.unit(), tree);
    var header = source.text().substring(start);
    var parenthesis = 0;
    for (int index = 0; index < header.length(); index++) {
      var character = header.charAt(index);
      if (character == '(') {
        parenthesis++;
      } else if (character == ')') {
        parenthesis--;
      } else if (character == '{' && parenthesis == 0) {
        return start + index;
      }
    }
    throw new IllegalArgumentException("type body not found: " + source.relativePath());
  }

  private static String memberHeader(QualityContext context, ParsedSource source, Tree member) {
    var positions = context.sources().docTrees().getSourcePositions();
    var start = (int) positions.getStartPosition(source.unit(), member);
    var end = (int) positions.getEndPosition(source.unit(), member);
    var raw = mask(source.text().substring(start, end)).trim();
    var body = topLevelBody(raw);
    if (body >= 0) {
      raw = raw.substring(0, body);
    }
    return raw.endsWith(";") ? raw.substring(0, raw.length() - 1) : raw;
  }

  private static int topLevelBody(String value) {
    var parenthesis = 0;
    for (int index = 0; index < value.length(); index++) {
      var character = value.charAt(index);
      if (character == '(') {
        parenthesis++;
      } else if (character == ')') {
        parenthesis--;
      } else if (character == '{' && parenthesis == 0) {
        return index;
      }
    }
    return -1;
  }

  private static boolean isEnumConstant(Tree member) {
    return member instanceof VariableTree variable
        && variable.getInitializer() instanceof NewClassTree
        && variable.getName().toString().matches("[A-Z][A-Z0-9_]*");
  }

  /** 与原 baseline 一样保留换行和引号，仅遮蔽注释及字面量内容。 */
  private static String mask(String text) {
    var result = new StringBuilder(text.length());
    var state = "code";
    for (int index = 0; index < text.length(); index++) {
      var character = text.charAt(index);
      var next = index + 1 < text.length() ? text.charAt(index + 1) : '\0';
      if ("code".equals(state)) {
        if (character == '/' && next == '/') {
          result.append("  ");
          index++;
          state = "line";
        } else if (character == '/' && next == '*') {
          result.append("  ");
          index++;
          state = "block";
        } else if (character == '"') {
          result.append(character);
          state = "string";
        } else if (character == '\'') {
          result.append(character);
          state = "char";
        } else {
          result.append(character);
        }
      } else if ("line".equals(state)) {
        result.append(character == '\n' ? '\n' : ' ');
        if (character == '\n') {
          state = "code";
        }
      } else if ("block".equals(state)) {
        if (character == '*' && next == '/') {
          result.append("  ");
          index++;
          state = "code";
        } else {
          result.append(character == '\n' ? '\n' : ' ');
        }
      } else if (character == '\\') {
        result.append("  ");
        index++;
      } else if (("string".equals(state) && character == '"')
          || ("char".equals(state) && character == '\'')) {
        result.append(character);
        state = "code";
      } else {
        result.append(character == '\n' ? '\n' : ' ');
      }
    }
    return result.toString();
  }

  private static String canonical(String value) {
    var current = value;
    String previous;
    do {
      previous = current;
      current = ANNOTATION.matcher(current).replaceAll("");
    } while (!previous.equals(current));
    return normalize(current);
  }

  private static String normalize(String value) {
    return SPACE.matcher(value).replaceAll(" ").trim();
  }

  private static String kind(ClassTree tree) {
    return switch (tree.getKind()) {
      case CLASS -> "class";
      case INTERFACE -> "interface";
      case ENUM -> "enum";
      case RECORD -> "record";
      case ANNOTATION_TYPE -> "@interface";
      default -> throw new IllegalArgumentException("unsupported public type: " + tree.getKind());
    };
  }

  private QualityViolation violation(String code, String message, String apiLine) {
    return new QualityViolation(
        id(),
        "config/api-snapshots/java-public-api.txt",
        1,
        code,
        message,
        apiLine.isEmpty() ? Map.of() : Map.of("apiLine", apiLine));
  }

  /**
   * 类型 AST 与直接嵌套类型。
   *
   * @param tree compiler 类型抽象语法树。
   * @param children 直接嵌套的类型节点。
   */
  private record TypeNode(ClassTree tree, List<TypeNode> children) {}

  /** 按源码嵌套层级收集类型节点，供公开 API 快照生成器稳定遍历。 */
  private static final class TypeCollector extends TreePathScanner<Void, List<TypeNode>> {
    private final ParsedSource source;

    private TypeCollector(ParsedSource source) {
      this.source = source;
    }

    private List<TypeNode> collect() {
      var roots = new ArrayList<TypeNode>();
      scan(source.unit(), roots);
      return roots;
    }

    @Override
    public Void visitClass(ClassTree tree, List<TypeNode> output) {
      var children = new ArrayList<TypeNode>();
      output.add(new TypeNode(tree, children));
      for (var member : tree.getMembers()) {
        if (member instanceof ClassTree nested) {
          visitClass(nested, children);
        }
      }
      return null;
    }
  }
}
